### ISSUE TITLE
front.jpg is very beefy! About 1.1M

### ISSUE THREAD

**Issue by bebraw** [antwarjs/antwarjs.github.io#1]
We should do something about it. Maybe this would be a good place to think about asset flow? We could pass the file through some optimizer for starters.

**Comment by eldh** [comment]
Yeah. A hook for plugins into the asset copying would be nice. For this, we should just do it manually though.

**Comment by bebraw** [comment]
I agree, a manual process is enough here.

Overall dealing with media is going to be bit of a challenge. Git doesn't scale that well with binaries. Maybe it doesn't make sense to maintain media in the same place for bigger blogs. We can get back to this later.

**Comment by eldh** [comment]
True. Though neither core nor default-theme makes any assumptions about where you store binary stuff, which I think is good. If people want to write plugins to deal with media in the assets that would be fine too.
